#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

cpp_falling_sand="$cmd_dir/cpp_falling_sand"

echo "Running main cpp_falling_sand"
$cpp_falling_sand || panic "cpp_falling_sand failed"
